### ISSUE TITLE
Create Twitter API

### ISSUE THREAD

**Issue by 0x3639** [zenon-network/twitter#1]
Looks like you need to setup the Twitter API and apply the secrets per these instructions.  I'm testing this workflow in my repo and cannot get it to run.  I think these is something wrong with the secrets, but I'm not sure.  I'll keep messing with it.  

https://github.com/twitter-together/action/blob/v3.0.0/docs/01-create-twitter-app.md

**Comment by sol-znn** [comment]
Ping me if you need assistance setting up your own workflow.

Currently, we can't be sure if this project is configured incorrectly.

**Comment by interstellartraveler77** [comment]
The necessary Github secrets have been configured under this repo:
```
TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
```
