### ISSUE TITLE
Community Tweet Fails with 403 Error

### ISSUE THREAD

**Issue by 0x3639** [zenon-network/twitter#16]
First community tweet failed with the following error on build.  

```
[Tweet](https://github.com/zenon-network/twitter/actions/runs/6132754362/job/16644028262#step:3:58)
ApiResponseError: Request failed with code 403
    at RequestHandlerHelper.createResponseError (/home/runner/work/_actions/twitter-together/action/v3/dist/index.js:17832:16)
    at RequestHandlerHelper.onResponseEndHandler (/home/runner/work/_actions/twitter-together/action/v3/dist/index.js:17981:25)
    at Gunzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  error: true,
  type: 'response',
  code: 403,
  headers: {
    date: 'Sat, 09 Sep 2023 19:31:26 UTC',
    perf: '7626143928',
    server: 'tsa_b',
    'set-cookie': [
      'guest_id_marketing=v1%3A169428788668361394; Max-Age=63072000; Expires=Mon, 08 Sep 2025 19:31:26 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'guest_id_ads=v1%3A169428788668361394; Max-Age=63072000; Expires=Mon, 08 Sep 2025 19:31:26 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'personalization_id="v1_A/jqFp+xtFv5cOi/9uEKAw=="; Max-Age=63072000; Expires=Mon, 08 Sep 2025 19:31:26 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'guest_id=v1%3A169428788668361394; Max-Age=63072000; Expires=Mon, 08 Sep 2025 19:31:26 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None'
    ],
    'api-version': '2.67',
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'no-cache, no-store, max-age=0',
    'content-length': '176',
    'x-access-level': 'read',
    'x-frame-options': 'SAMEORIGIN',
    'content-encoding': 'gzip',
    'x-transaction-id': '7a0cfa5123abb3aa',
    'x-xss-protection': '0',
    'x-rate-limit-limit': '40000',
    'x-rate-limit-reset': '1694288176',
    'content-disposition': 'attachment; filename=json.json',
    'x-content-type-options': 'nosniff',
    'x-rate-limit-remaining': '39998',
    'strict-transport-security': 'max-age=631138519',
    'x-response-time': '13',
    'x-connection-hash': '19607208a6b4d387b8aee770eb2a9e1977f1abd19edead0459533355ca3f490a',
    connection: 'close'
  },
  rateLimit: { limit: 40000, remaining: 39998, reset: 1694288176 },
  data: {
    title: 'Forbidden',
    status: 403,
    detail: 'Your client app is not configured with the appropriate oauth1 app permissions for this endpoint.',
    type: 'https://api.twitter.com/2/problems/oauth1-permissions'
  }
}
```

**Comment by 0x3639** [comment]
@interstellartraveler77 looks like we have an API setup issue with tweet with me.  I do not think this is something I can fix from my end.  You will need to log into twitter and fix the settings.  I will post settings that work for me.

**Comment by 0x3639** [comment]
![image](https://github.com/zenon-network/twitter/assets/5406130/3de531cc-2ed9-4b31-9069-4fd3afab68b3)

![image](https://github.com/zenon-network/twitter/assets/5406130/37b70dcb-7f78-4add-89fe-1270787b0d7d)

**Comment by 0x3639** [comment]
This appears wrong

![image](https://github.com/zenon-network/twitter/assets/5406130/9f8922e3-8a33-49b8-be6a-2aa671568216)

It should look like this

![image](https://github.com/zenon-network/twitter/assets/5406130/e2408ef0-e1d1-42b4-ac12-b2d5bd4c99de)

**Comment by 0x3639** [comment]
@Sol-Sanctum do you have TWITTER_BEARER_TOKEN in your setup?  If not I'm going to delete it here.

**Comment by 0x3639** [comment]
Here are the API setup instructions.  I got this 403 error we are experiencing when I setup the API keys wrong for learn_zenon

https://github.com/twitter-together/action/blob/main/docs/01-create-twitter-app.md

**Comment by sol-znn** [comment]
> @Sol-Sanctum do you have TWITTER_BEARER_TOKEN in your setup? If not I'm going to delete it here.

I don't use that token in my repo.
Perhaps @interstellartraveler77 needs to regenerate the keys.

**Comment by 0x3639** [comment]
I removed TWITTER_BEARER_TOKEN and re-ran the action.  Got the same error.  I think @interstellartraveler77 needs to check the setup for `App Permissions` and `Type of App` in the developer console of twitter.  If those are setup correctly, I recommend reissuing the tokens and replace the variables in github.  

I recall getting the 403 error with the incorrect Type of App.

**Comment by 0x3639** [comment]
I received new API information and have inserted those secrets.  Now the community needs to make a PR for a tweet.
